# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import server2_pb2 as server2__pb2


class GetControllerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.List = channel.unary_unary(
        '/blog_proto.GetController/List',
        request_serializer=server2__pb2.GetListRequest.SerializeToString,
        response_deserializer=server2__pb2.BlogPost.FromString,
        )


class GetControllerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def List(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GetControllerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'List': grpc.unary_unary_rpc_method_handler(
          servicer.List,
          request_deserializer=server2__pb2.GetListRequest.FromString,
          response_serializer=server2__pb2.BlogPost.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'blog_proto.GetController', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
